#pragma kernel k
StructuredBuffer<uint> b;
RWTexture2D<float4> r;

int w;
int h;
float4 t;
float4 f;

[numthreads(64,1,1)]
void k (uint3 id : SV_DispatchThreadID)
{
    uint wordIndex = id.x;

    uint word = b[wordIndex];

    uint basePixel = wordIndex * 32;

    for (uint bit = 0; bit < 32; bit++)
    {
        uint pixel = basePixel + bit;

        if (pixel >= w * h)
            break;

        uint x = pixel % w;
        uint y = pixel / w;

        uint value = (word >> bit) & 1u;

        r[int2(x,y)] = value ? t : f;
    }
}